<?php defined('BASEPATH') OR exit('No direct script access allowed');
//DO NOT EDIT THIS FILE

//ClassMap for autoloader
$classes = array (
  'GoCart\\Controller\\AdminAmbil' => 'D:\\LABS\\xampp\\htdocs\\gocart/addons\\ambil-sendiri\\controllers\\AdminAmbil.php',
  'GoCart\\Controller\\Ambil' => 'D:\\LABS\\xampp\\htdocs\\gocart/addons\\ambil-sendiri\\controllers\\Ambil.php',
  'GoCart\\Controller\\AdminCod' => 'D:\\LABS\\xampp\\htdocs\\gocart/addons\\cod\\controllers\\AdminCod.php',
  'GoCart\\Controller\\Cod' => 'D:\\LABS\\xampp\\htdocs\\gocart/addons\\cod\\controllers\\Cod.php',
  'GoCart\\Controller\\AdminGoJek' => 'D:\\LABS\\xampp\\htdocs\\gocart/addons\\gojek\\controllers\\AdminGoJek.php',
  'GoCart\\Controller\\GoJek' => 'D:\\LABS\\xampp\\htdocs\\gocart/addons\\gojek\\controllers\\GoJek.php',
  'GoCart\\Controller\\Addresses' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\addresses\\controllers\\Addresses.php',
  'GoCart\\Controller\\AdminBanners' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\banners\\controllers\\Banners.php',
  'Banners' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\banners\\models\\Banners.php',
  'GoCart\\Controller\\Cart' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\cart\\controllers\\Cart.php',
  'GoCart\\Controller\\AdminCategories' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\categories\\controllers\\AdminCategories.php',
  'GoCart\\Controller\\Category' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\categories\\controllers\\Category.php',
  'Categories' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\categories\\models\\Categories.php',
  'GoCart\\Controller\\Checkout' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\checkout\\controllers\\Checkout.php',
  'GoCart\\Controller\\AdminCoupons' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\coupons\\controllers\\AdminCoupons.php',
  'Coupons' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\coupons\\models\\Coupons.php',
  'GoCart\\Controller\\AdminCustomers' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\customers\\controllers\\AdminCustomers.php',
  'Customers' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\customers\\models\\Customers.php',
  'GoCart\\Controller\\AdminDashboard' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\dashboard\\controllers\\AdminDashboard.php',
  'GoCart\\Controller\\AdminDigitalProducts' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\digital_products\\controllers\\AdminDigitalProducts.php',
  'GoCart\\Controller\\DigitalProducts' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\digital_products\\controllers\\DigitalProducts.php',
  'DigitalProducts' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\digital_products\\models\\Digitalproducts.php',
  'GoCart\\Controller\\AdminGiftCards' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\gift_cards\\controllers\\AdminGiftCards.php',
  'GiftCards' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\gift_cards\\models\\Giftcards.php',
  'GoCart\\Controller\\AdminLocations' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\locations\\controllers\\AdminLocations.php',
  'Locations' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\locations\\models\\Locations.php',
  'GoCart\\Controller\\AdminLogin' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\login\\controllers\\AdminLogin.php',
  'GoCart\\Controller\\Login' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\login\\controllers\\Login.php',
  'Login' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\login\\models\\Login.php',
  'GoCart\\Controller\\MyAccount' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\my_account\\controllers\\MyAccount.php',
  'GoCart\\Controller\\AdminOrders' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\orders\\controllers\\AdminOrders.php',
  'Orders' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\orders\\models\\Orders.php',
  'GoCart\\Controller\\AdminPages' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\pages\\controllers\\AdminPages.php',
  'GoCart\\Controller\\Page' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\pages\\controllers\\Page.php',
  'Pages' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\pages\\models\\Pages.php',
  'GoCart\\Controller\\AdminPayments' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\payments\\controllers\\AdminPayments.php',
  'GoCart\\Controller\\AdminProducts' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\products\\controllers\\AdminProducts.php',
  'GoCart\\Controller\\Product' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\products\\controllers\\Product.php',
  'ProductOptions' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\products\\models\\Productoptions.php',
  'Products' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\products\\models\\Products.php',
  'GoCart\\Controller\\AdminReports' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\reports\\controllers\\AdminReports.php',
  'GoCart\\Controller\\Search' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\search\\controllers\\Search.php',
  'Search' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\search\\models\\Search.php',
  'GoCart\\Controller\\AdminSettings' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\settings\\controllers\\AdminSettings.php',
  'Messages' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\settings\\models\\Messages.php',
  'Settings' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\settings\\models\\Settings.php',
  'GoCart\\Controller\\AdminShipping' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\shipping\\controllers\\AdminShipping.php',
  'GoCart\\Controller\\AdminSitemap' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\sitemap\\controllers\\AdminSitemap.php',
  'Tax' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\tax\\models\\Tax.php',
  'GoCart\\Controller\\AdminUsers' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\users\\controllers\\AdminUsers.php',
  'GoCart\\Controller\\AdminWysiwyg' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules\\wysiwyg\\controllers\\AdminWysiwyg.php',
  'Auth' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\libraries\\Auth.php',
  'Breadcrumbs' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\libraries\\Breadcrumbs.php',
  'GoCart\\Emails' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\libraries\\Emails.php',
  'MY_Form_validation' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\libraries\\MY_Form_validation.php',
  'MY_Image_lib' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\libraries\\MY_Image_lib.php',
  'Session' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\libraries\\Session.php',
  'xmlparser' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\libraries\\xmlparser.php',
  'GoCart\\Controller\\Admin' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\core\\AdminController.php',
  'CI' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\core\\CI.php',
  'GoCart\\Controller' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\core\\Controller.php',
  'GoCart\\Controller\\Front' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\core\\FrontController.php',
  'GC' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\core\\GC.php',
  'GoCart' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\core\\GoCart.php',
  'GoCart\\Libraries\\View' => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\core\\View.php',
);

//Available Payment Modules
$GLOBALS['paymentModules'] =array (
  0 => 
  array (
    'name' => 'Charge on Delivery',
    'key' => 'cod',
    'class' => 'Cod',
  ),
);

//Available Shipping Modules
$GLOBALS['shippingModules'] = array (
  0 => 
  array (
    'name' => 'Ambil Sendiri',
    'key' => 'ambil-sendiri',
    'class' => 'Ambil',
  ),
  1 => 
  array (
    'name' => 'GoJek',
    'key' => 'gojek',
    'class' => 'GoJek',
  ),
);

//
$GLOBALS['uploadModules'] = array (
  0 => 
  array (
    'name' => 'Upload File',
    'key' => 'upload-file',
    'class' => 'upload',
  ),
);

//Theme Shortcodes
$GLOBALS['themeShortcodes'] = array (
  0 => 
  array (
    'shortcode' => 'banner',
    'method' => 
    array (
      0 => 'Banners',
      1 => 'show_collection',
    ),
  ),
  1 => 
  array (
    'shortcode' => 'category',
    'method' => 
    array (
      0 => 'GoCart\\Controller\\Category',
      1 => 'shortcode',
    ),
  ),
);

//Complete Module List
$GLOBALS['modules'] = array (
  0 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/addresses',
  1 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/banners',
  2 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/cart',
  3 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/categories',
  4 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/checkout',
  5 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/coupons',
  6 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/customers',
  7 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/dashboard',
  8 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/digital_products',
  9 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/gift_cards',
  10 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/locations',
  11 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/login',
  12 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/my_account',
  13 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/orders',
  14 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/pages',
  15 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/payments',
  16 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/products',
  17 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/reports',
  18 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/search',
  19 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/settings',
  20 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/shipping',
  21 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/sitemap',
  22 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/tax',
  23 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/users',
  24 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/wysiwyg',
  25 => 'D:\\LABS\\xampp\\htdocs\\gocart/addons/ambil-sendiri',
  26 => 'D:\\LABS\\xampp\\htdocs\\gocart/addons/cod',
  27 => 'D:\\LABS\\xampp\\htdocs\\gocart/addons/gojek',
  28 => 'D:\\LABS\\xampp\\htdocs\\gocart\\application\\modules/upload',
);

//Defined Routes
$routes = array (
  0 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/ambil-sendiri/form',
    2 => 'GoCart\\Controller\\AdminAmbil#form',
  ),
  1 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/ambil-sendiri/install',
    2 => 'GoCart\\Controller\\AdminAmbil#install',
  ),
  2 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/ambil-sendiri/uninstall',
    2 => 'GoCart\\Controller\\AdminAmbil#uninstall',
  ),
  3 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/cod/form',
    2 => 'GoCart\\Controller\\AdminCod#form',
  ),
  4 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/cod/install',
    2 => 'GoCart\\Controller\\AdminCod#install',
  ),
  5 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/cod/uninstall',
    2 => 'GoCart\\Controller\\AdminCod#uninstall',
  ),
  6 => 
  array (
    0 => 'GET|POST',
    1 => '/cod/process-payment',
    2 => 'GoCart\\Controller\\Cod#processPayment',
  ),
  7 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/gojek/form',
    2 => 'GoCart\\Controller\\AdminGoJek#form',
  ),
  8 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/gojek/install',
    2 => 'GoCart\\Controller\\AdminGoJek#install',
  ),
  9 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/gojek/uninstall',
    2 => 'GoCart\\Controller\\AdminGoJek#uninstall',
  ),
  10 => 
  array (
    0 => 'GET|POST',
    1 => '/addresses',
    2 => 'GoCart\\Controller\\Addresses#index',
  ),
  11 => 
  array (
    0 => 'GET|POST',
    1 => '/addresses/json',
    2 => 'GoCart\\Controller\\Addresses#addressJSON',
  ),
  12 => 
  array (
    0 => 'GET|POST',
    1 => '/addresses/form/[i:id]?',
    2 => 'GoCart\\Controller\\Addresses#form',
  ),
  13 => 
  array (
    0 => 'GET|POST',
    1 => '/addresses/delete/[i:id]',
    2 => 'GoCart\\Controller\\Addresses#delete',
  ),
  14 => 
  array (
    0 => 'GET|POST',
    1 => '/addresses/get-zone-options/[i:id]',
    2 => 'GoCart\\Controller\\Addresses#getZoneOptions',
  ),
  15 => 
  array (
    0 => 'GET',
    1 => '/admin/banners',
    2 => 'GoCart\\Controller\\AdminBanners#index',
  ),
  16 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/banners/banner_collection_form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminBanners#banner_collection_form',
  ),
  17 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/banners/delete_banner_collection/[i:id]',
    2 => 'GoCart\\Controller\\AdminBanners#delete_banner_collection',
  ),
  18 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/banners/banner_collection/[i:id]',
    2 => 'GoCart\\Controller\\AdminBanners#banner_collection',
  ),
  19 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/banners/banner_form/[i:banner_collection_id]/[i:id]?',
    2 => 'GoCart\\Controller\\AdminBanners#banner_form',
  ),
  20 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/banners/delete_banner/[i:id]',
    2 => 'GoCart\\Controller\\AdminBanners#delete_banner',
  ),
  21 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/banners/organize',
    2 => 'GoCart\\Controller\\AdminBanners#organize',
  ),
  22 => 
  array (
    0 => 'GET|POST',
    1 => '/cart/summary',
    2 => 'GoCart\\Controller\\Cart#summary',
  ),
  23 => 
  array (
    0 => 'GET|POST',
    1 => '/cart/add-to-cart',
    2 => 'GoCart\\Controller\\Cart#addToCart',
  ),
  24 => 
  array (
    0 => 'GET|POST',
    1 => '/cart/update-cart',
    2 => 'GoCart\\Controller\\Cart#updateCart',
  ),
  25 => 
  array (
    0 => 'GET|POST',
    1 => '/cart/submit-coupon',
    2 => 'GoCart\\Controller\\Cart#submitCoupon',
  ),
  26 => 
  array (
    0 => 'GET|POST',
    1 => '/cart/submit-gift-card',
    2 => 'GoCart\\Controller\\Cart#submitGiftCard',
  ),
  27 => 
  array (
    0 => 'GET',
    1 => '/admin/categories',
    2 => 'GoCart\\Controller\\AdminCategories#index',
  ),
  28 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/categories/form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminCategories#form',
  ),
  29 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/categories/delete/[i:id]',
    2 => 'GoCart\\Controller\\AdminCategories#delete',
  ),
  30 => 
  array (
    0 => 'GET|POST',
    1 => '/category/[:slug]/[:sort]?/[:dir]?/[:page]?',
    2 => 'GoCart\\Controller\\Category#index',
  ),
  31 => 
  array (
    0 => 'GET|POST',
    1 => '/checkout',
    2 => 'GoCart\\Controller\\Checkout#index',
  ),
  32 => 
  array (
    0 => 'GET|POST',
    1 => '/checkout/address-list',
    2 => 'GoCart\\Controller\\Checkout#addressList',
  ),
  33 => 
  array (
    0 => 'GET|POST',
    1 => '/checkout/submit-order',
    2 => 'GoCart\\Controller\\Checkout#submitOrder',
  ),
  34 => 
  array (
    0 => 'GET|POST',
    1 => '/order-complete/[:order_id]',
    2 => 'GoCart\\Controller\\Checkout#orderComplete',
  ),
  35 => 
  array (
    0 => 'GET|POST',
    1 => '/order-complete-email/[:order_id]',
    2 => 'GoCart\\Controller\\Checkout#orderCompleteEmail',
  ),
  36 => 
  array (
    0 => 'GET|POST',
    1 => '/checkout/address',
    2 => 'GoCart\\Controller\\Checkout#address',
  ),
  37 => 
  array (
    0 => 'GET|POST',
    1 => '/checkout/payment-methods',
    2 => 'GoCart\\Controller\\Checkout#paymentMethods',
  ),
  38 => 
  array (
    0 => 'GET|POST',
    1 => '/checkout/shipping-methods',
    2 => 'GoCart\\Controller\\Checkout#shippingMethods',
  ),
  39 => 
  array (
    0 => 'GET|POST',
    1 => '/checkout/set-shipping-method',
    2 => 'GoCart\\Controller\\Checkout#setShippingMethod',
  ),
  40 => 
  array (
    0 => 'GET',
    1 => '/admin/coupons',
    2 => 'GoCart\\Controller\\AdminCoupons#index',
  ),
  41 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/coupons/form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminCoupons#form',
  ),
  42 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/coupons/delete/[i:id]',
    2 => 'GoCart\\Controller\\AdminCoupons#delete',
  ),
  43 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/export',
    2 => 'GoCart\\Controller\\AdminCustomers#export',
  ),
  44 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/get_subscriber_list',
    2 => 'GoCart\\Controller\\AdminCustomers#getSubscriberList',
  ),
  45 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminCustomers#form',
  ),
  46 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/addresses/[i:id]',
    2 => 'GoCart\\Controller\\AdminCustomers#addresses',
  ),
  47 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/delete/[i:id]?',
    2 => 'GoCart\\Controller\\AdminCustomers#delete',
  ),
  48 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/groups',
    2 => 'GoCart\\Controller\\AdminCustomers#groups',
  ),
  49 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/group_form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminCustomers#groupForm',
  ),
  50 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/delete_group/[i:id]?',
    2 => 'GoCart\\Controller\\AdminCustomers#deleteGroup',
  ),
  51 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/address_list/[i:id]?',
    2 => 'GoCart\\Controller\\AdminCustomers#addressList',
  ),
  52 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/address_form/[i:customer_id]/[i:id]?',
    2 => 'GoCart\\Controller\\AdminCustomers#addressForm',
  ),
  53 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/delete_address/[i:customer_id]/[i:id]',
    2 => 'GoCart\\Controller\\AdminCustomers#deleteAddress',
  ),
  54 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/customers/[:order_by]?/[:direction]?/[i:page]?',
    2 => 'GoCart\\Controller\\AdminCustomers#index',
  ),
  55 => 
  array (
    0 => 'GET',
    1 => '/admin/dashboard',
    2 => 'GoCart\\Controller\\AdminDashboard#index',
  ),
  56 => 
  array (
    0 => 'GET',
    1 => '/admin',
    2 => 'GoCart\\Controller\\AdminDashboard#index',
  ),
  57 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/digital_products/form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminDigitalProducts#form',
  ),
  58 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/digital_products/delete/[i:id]',
    2 => 'GoCart\\Controller\\AdminDigitalProducts#delete',
  ),
  59 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/digital_products',
    2 => 'GoCart\\Controller\\AdminDigitalProducts#index',
  ),
  60 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/gift-cards/form',
    2 => 'GoCart\\Controller\\AdminGiftCards#form',
  ),
  61 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/gift-cards/delete/[i:id]',
    2 => 'GoCart\\Controller\\AdminGiftCards#delete',
  ),
  62 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/gift-cards/enable',
    2 => 'GoCart\\Controller\\AdminGiftCards#enable',
  ),
  63 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/gift-cards/disable',
    2 => 'GoCart\\Controller\\AdminGiftCards#disable',
  ),
  64 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/gift-cards/settings',
    2 => 'GoCart\\Controller\\AdminGiftCards#settings',
  ),
  65 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/gift-cards',
    2 => 'GoCart\\Controller\\AdminGiftCards#index',
  ),
  66 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/zone_areas/[i:id]',
    2 => 'GoCart\\Controller\\AdminLocations#zone_areas',
  ),
  67 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/delete_zone_area/[i:id]',
    2 => 'GoCart\\Controller\\AdminLocations#delete_zone_area',
  ),
  68 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/zone_area_form/[i:zone_id]/[i:id]?',
    2 => 'GoCart\\Controller\\AdminLocations#zone_area_form',
  ),
  69 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/zones/[i:id]',
    2 => 'GoCart\\Controller\\AdminLocations#zones',
  ),
  70 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/zone_form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminLocations#zone_form',
  ),
  71 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/delete_zone/[i:id]',
    2 => 'GoCart\\Controller\\AdminLocations#delete_zone',
  ),
  72 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/get_zone_menu',
    2 => 'GoCart\\Controller\\AdminLocations#get_zone_menu',
  ),
  73 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/country_form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminLocations#country_form',
  ),
  74 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/delete_country/[i:id]',
    2 => 'GoCart\\Controller\\AdminLocations#delete_country',
  ),
  75 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations/organize_countries',
    2 => 'GoCart\\Controller\\AdminLocations#organize_countries',
  ),
  76 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/locations',
    2 => 'GoCart\\Controller\\AdminLocations#index',
  ),
  77 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/login',
    2 => 'GoCart\\Controller\\AdminLogin#login',
  ),
  78 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/logout',
    2 => 'GoCart\\Controller\\AdminLogin#logout',
  ),
  79 => 
  array (
    0 => 'GET|POST',
    1 => '/login/[:redirect]?',
    2 => 'GoCart\\Controller\\Login#login',
  ),
  80 => 
  array (
    0 => 'GET|POST',
    1 => '/logout',
    2 => 'GoCart\\Controller\\Login#logout',
  ),
  81 => 
  array (
    0 => 'GET|POST',
    1 => '/forgot-password',
    2 => 'GoCart\\Controller\\Login#forgotPassword',
  ),
  82 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/forgot-password',
    2 => 'GoCart\\Controller\\AdminLogin#forgotPassword',
  ),
  83 => 
  array (
    0 => 'GET|POST',
    1 => '/register',
    2 => 'GoCart\\Controller\\Login#register',
  ),
  84 => 
  array (
    0 => 'GET|POST',
    1 => '/my-account',
    2 => 'GoCart\\Controller\\MyAccount#index',
  ),
  85 => 
  array (
    0 => 'GET|POST',
    1 => '/my-account/downloads',
    2 => 'GoCart\\Controller\\MyAccount#downloads',
  ),
  86 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders/form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminOrders#form',
  ),
  87 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders/export',
    2 => 'GoCart\\Controller\\AdminOrders#export',
  ),
  88 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders/bulk_delete',
    2 => 'GoCart\\Controller\\AdminOrders#bulk_delete',
  ),
  89 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders/order/[:orderNumber]',
    2 => 'GoCart\\Controller\\AdminOrders#order',
  ),
  90 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders/sendNotification/[:orderNumber]',
    2 => 'GoCart\\Controller\\AdminOrders#sendNotification',
  ),
  91 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders/packing_slip/[:orderNumber]',
    2 => 'GoCart\\Controller\\AdminOrders#packing_slip',
  ),
  92 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders/edit_status',
    2 => 'GoCart\\Controller\\AdminOrders#edit_status',
  ),
  93 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders/delete/[i:id]',
    2 => 'GoCart\\Controller\\AdminOrders#delete',
  ),
  94 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders',
    2 => 'GoCart\\Controller\\AdminOrders#index',
  ),
  95 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/orders/index/[:orderBy]?/[:orderDir]?/[:code]?/[i:page]?',
    2 => 'GoCart\\Controller\\AdminOrders#index',
  ),
  96 => 
  array (
    0 => 'GET|POST',
    1 => '/digital-products/download/[i:fileId]/[i:orderId]',
    2 => 'GoCart\\Controller\\DigitalProducts#download',
  ),
  97 => 
  array (
    0 => 'GET',
    1 => '/admin/pages',
    2 => 'GoCart\\Controller\\AdminPages#index',
  ),
  98 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/pages/form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminPages#form',
  ),
  99 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/pages/link_form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminPages#link_form',
  ),
  100 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/pages/delete/[i:id]',
    2 => 'GoCart\\Controller\\AdminPages#delete',
  ),
  101 => 
  array (
    0 => 'GET|POST',
    1 => '/page/[:slug]',
    2 => 'GoCart\\Controller\\Page#index',
  ),
  102 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/payments',
    2 => 'GoCart\\Controller\\AdminPayments#index',
  ),
  103 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/products/product_autocomplete',
    2 => 'GoCart\\Controller\\AdminProducts#product_autocomplete',
  ),
  104 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/products/bulk_save',
    2 => 'GoCart\\Controller\\AdminProducts#bulk_save',
  ),
  105 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/products/product_image_form',
    2 => 'GoCart\\Controller\\AdminProducts#product_image_form',
  ),
  106 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/products/product_image_upload',
    2 => 'GoCart\\Controller\\AdminProducts#product_image_upload',
  ),
  107 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/products/form/[i:id]?/[i:copy]?',
    2 => 'GoCart\\Controller\\AdminProducts#form',
  ),
  108 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/products/gift-card-form/[i:id]?/[i:copy]?',
    2 => 'GoCart\\Controller\\AdminProducts#giftCardForm',
  ),
  109 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/products/delete/[i:id]',
    2 => 'GoCart\\Controller\\AdminProducts#delete',
  ),
  110 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/products/[i:rows]?/[:order_by]?/[:sort_order]?/[:code]?/[i:page]?',
    2 => 'GoCart\\Controller\\AdminProducts#index',
  ),
  111 => 
  array (
    0 => 'GET|POST',
    1 => '/product/[:slug]',
    2 => 'GoCart\\Controller\\Product#index',
  ),
  112 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/reports',
    2 => 'GoCart\\Controller\\AdminReports#index',
  ),
  113 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/reports/best_sellers',
    2 => 'GoCart\\Controller\\AdminReports#best_sellers',
  ),
  114 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/reports/sales',
    2 => 'GoCart\\Controller\\AdminReports#sales',
  ),
  115 => 
  array (
    0 => 'GET|POST',
    1 => '/search/[:code]?/[:sort]?/[:dir]?/[:page]?',
    2 => 'GoCart\\Controller\\Search#index',
  ),
  116 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/settings',
    2 => 'GoCart\\Controller\\AdminSettings#index',
  ),
  117 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/settings/canned_messages',
    2 => 'GoCart\\Controller\\AdminSettings#canned_messages',
  ),
  118 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/settings/canned_message_form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminSettings#canned_message_form',
  ),
  119 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/settings/delete_message/[i:id]',
    2 => 'GoCart\\Controller\\AdminSettings#delete_message',
  ),
  120 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/shipping',
    2 => 'GoCart\\Controller\\AdminShipping#index',
  ),
  121 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/sitemap',
    2 => 'GoCart\\Controller\\AdminSitemap#index',
  ),
  122 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/sitemap/new-sitemap',
    2 => 'GoCart\\Controller\\AdminSitemap#newSitemap',
  ),
  123 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/sitemap/generate-products',
    2 => 'GoCart\\Controller\\AdminSitemap#generateProducts',
  ),
  124 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/sitemap/generate-pages',
    2 => 'GoCart\\Controller\\AdminSitemap#generatePages',
  ),
  125 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/sitemap/generate-categories',
    2 => 'GoCart\\Controller\\AdminSitemap#generateCategories',
  ),
  126 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/sitemap/complete-sitemap',
    2 => 'GoCart\\Controller\\AdminSitemap#completeSitemap',
  ),
  127 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/users',
    2 => 'GoCart\\Controller\\AdminUsers#index',
  ),
  128 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/users/form/[i:id]?',
    2 => 'GoCart\\Controller\\AdminUsers#form',
  ),
  129 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/users/delete/[i:id]',
    2 => 'GoCart\\Controller\\AdminUsers#delete',
  ),
  130 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/wysiwyg/upload_image',
    2 => 'GoCart\\Controller\\AdminWysiwyg#upload_image',
  ),
  131 => 
  array (
    0 => 'GET|POST',
    1 => '/admin/wysiwyg/get_images',
    2 => 'GoCart\\Controller\\AdminWysiwyg#get_images',
  ),
);